import { Injectable } from '@angular/core';
import { Account } from './classes/account';
import { Response } from './classes/response';
import { JOHN } from './data/johnAccount';

@Injectable()
/**
 * This service handles the following:
 *   1. Account creation
 *   2. Retrieving user information -> profile page
 *   3. Logging in
 */
export class AccountService {

  constructor() { }

  /**
   * Create an account based on the given parameters.
   * A user id is generated by hashing the email address
   * 
   * @param accountDetails the details of the account
   */
  createAccount(accountDetails: Account): Promise<Response> {
    
    return Promise.resolve(null); // STUB METHOD
  }
  
  /**
   * Check the email address given to make sure it's not a registered email
   * 
   * @param email the email address to be checked
   */
  checkEmail(email: string): Promise<Response> {

    return Promise.resolve(new Response(true, 'All good'));
  }

  /**
   * Try to log a user in, and return the response from the server
   * 
   * @param email the email, and also the id, of the account
   * @param password self explanatory
   */
  login(email: string, password: string): Promise<Response> {
    
    return Promise.resolve(new Response(true, 'All good'));
  }
  
  /**
   * 
   * @param id - the id of the user, should be calculated from the email
   */
  getUserInformation(id: string): Promise<Account> {
    /*
     * If id doesn't exist, will call Promise.reject('message')
     */
    
    return Promise.resolve(JOHN);
  }
  
  /**
   * Send request to server to edit the user's information, 
   * based on the given account details, and return server's response
   * 
   * @param id - the id of the user, just for double-checking
   * @param account - the object containing all information to be updated
   */
  editUserInformation(id: string, account: Account): Promise<Response> {
    
    return Promise.resolve(new Response(true, 'All good'));
  }

}
